"""initial_schema

Revision ID: d14b378f0c8d
Revises: 
Create Date: 2026-06-15 19:29:15.518845+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd14b378f0c8d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('pine_script_config', sa.String(length=100), nullable=True),
    sa.Column('contract_type', sa.String(length=30), nullable=True),
    sa.Column('session_config_json', sa.JSON(), nullable=True),
    sa.Column('allowed_days_json', sa.JSON(), nullable=True),
    sa.Column('sl_atr_multiplier', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('tp_atr_multiplier', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('atr_period', sa.Integer(), nullable=False),
    sa.Column('atr_timeframe', sa.String(length=10), nullable=True),
    sa.Column('max_trades_day', sa.Integer(), nullable=True),
    sa.Column('daily_loss_stop', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('max_quantity', sa.Integer(), nullable=True),
    sa.Column('max_open_positions_symbol', sa.Integer(), nullable=False),
    sa.Column('score_minimum', sa.Integer(), nullable=True),
    sa.Column('allow_reversal', sa.Boolean(), nullable=False),
    sa.Column('cooldown_minutes', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('actor', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('object_type', sa.String(length=50), nullable=False),
    sa.Column('object_id', sa.String(length=100), nullable=True),
    sa.Column('old_value_json', sa.JSON(), nullable=True),
    sa.Column('new_value_json', sa.JSON(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_actor', 'audit_logs', ['actor'], unique=False)
    op.create_index('ix_audit_logs_created_at', 'audit_logs', ['created_at'], unique=False)
    op.create_index('ix_audit_logs_object_type_id', 'audit_logs', ['object_type', 'object_id'], unique=False)
    op.create_table('economic_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('impact', sa.String(length=10), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('actual', sa.String(length=50), nullable=True),
    sa.Column('forecast', sa.String(length=50), nullable=True),
    sa.Column('previous', sa.String(length=50), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_economic_events_event_time', 'economic_events', ['event_time'], unique=False)
    op.create_index('ix_economic_events_impact', 'economic_events', ['impact'], unique=False)
    op.create_table('global_profile',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('profile_name', sa.String(length=50), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('days_enabled_json', sa.JSON(), nullable=False),
    sa.Column('entry_start_time', sa.Time(), nullable=True),
    sa.Column('entry_end_time', sa.Time(), nullable=True),
    sa.Column('allow_exits_outside_window', sa.Boolean(), nullable=False),
    sa.Column('allow_overnight', sa.Boolean(), nullable=False),
    sa.Column('force_flat_time', sa.Time(), nullable=True),
    sa.Column('news_filter_enabled', sa.Boolean(), nullable=False),
    sa.Column('news_window_minutes', sa.Integer(), nullable=False),
    sa.Column('news_impact_levels_json', sa.JSON(), nullable=False),
    sa.Column('max_open_positions', sa.Integer(), nullable=False),
    sa.Column('daily_loss_stop', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('global_daily_profit_lock', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('entry_cutoff_time', sa.Time(), nullable=True),
    sa.Column('max_holding_minutes', sa.Integer(), nullable=True),
    sa.Column('score_minimum', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(length=30), nullable=False),
    sa.Column('traderspost_enabled', sa.Boolean(), nullable=False),
    sa.Column('dry_run', sa.Boolean(), nullable=False),
    sa.Column('default_quantity', sa.Integer(), nullable=False),
    sa.Column('retry_attempts', sa.Integer(), nullable=False),
    sa.Column('retry_backoff_seconds', sa.Integer(), nullable=False),
    sa.Column('entry_signal_timeout_secs', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('market_data_status',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('heartbeat_age_seconds', sa.Integer(), nullable=True),
    sa.Column('last_atr_5m', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('last_atr_15m', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('last_atr_1h', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('bars_available_json', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol')
    )
    op.create_table('ohlcv_bars',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('timeframe', sa.String(length=20), nullable=False),
    sa.Column('bar_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('high', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('low', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('close', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('volume', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'timeframe', 'bar_time', 'provider', name='uq_ohlcv_symbol_tf_time_provider')
    )
    op.create_index('ix_ohlcv_bars_symbol_tf_time', 'ohlcv_bars', ['symbol', 'timeframe', 'bar_time'], unique=False)
    op.create_table('position_states',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('strategy_id', sa.String(length=100), nullable=True),
    sa.Column('account_id', sa.String(length=100), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('state', sa.String(length=30), nullable=False),
    sa.Column('state_source', sa.String(length=20), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('entry_signal_id', sa.Uuid(), nullable=True),
    sa.Column('risk_plan_json', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'symbol', name='uq_position_account_symbol')
    )
    op.create_table('raw_signals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('strategy_id', sa.String(length=100), nullable=False),
    sa.Column('ticker_received', sa.String(length=50), nullable=True),
    sa.Column('action', sa.String(length=20), nullable=True),
    sa.Column('sentiment', sa.String(length=20), nullable=True),
    sa.Column('quantity_raw', sa.String(length=20), nullable=True),
    sa.Column('price_raw', sa.String(length=50), nullable=True),
    sa.Column('time_raw', sa.String(length=50), nullable=True),
    sa.Column('interval_raw', sa.String(length=20), nullable=True),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('headers_json', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('token_valid', sa.Boolean(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_raw_signals_received_at', 'raw_signals', ['received_at'], unique=False)
    op.create_index('ix_raw_signals_strategy_id', 'raw_signals', ['strategy_id'], unique=False)
    op.create_table('strategy_performance',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('strategy_id', sa.String(length=100), nullable=False),
    sa.Column('total_signals_received', sa.Integer(), nullable=False),
    sa.Column('total_approved', sa.Integer(), nullable=False),
    sa.Column('total_blocked', sa.Integer(), nullable=False),
    sa.Column('total_signals_sent', sa.Integer(), nullable=False),
    sa.Column('filter_pass_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('avg_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('blocks_level_1', sa.Integer(), nullable=False),
    sa.Column('blocks_level_2', sa.Integer(), nullable=False),
    sa.Column('blocks_level_3', sa.Integer(), nullable=False),
    sa.Column('blocks_level_4', sa.Integer(), nullable=False),
    sa.Column('blocks_level_5', sa.Integer(), nullable=False),
    sa.Column('top_block_reasons_json', sa.JSON(), nullable=True),
    sa.Column('first_signal_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_signal_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('strategy_id')
    )
    op.create_table('strategy_templates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('strategy_type', sa.String(length=50), nullable=True),
    sa.Column('default_config_json', sa.JSON(), nullable=True),
    sa.Column('typical_metrics_json', sa.JSON(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('symbol_maps',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tv_symbol', sa.String(length=50), nullable=False),
    sa.Column('mapped_symbol', sa.String(length=50), nullable=False),
    sa.Column('exchange', sa.String(length=20), nullable=False),
    sa.Column('contract_type', sa.String(length=30), nullable=False),
    sa.Column('underlying_name', sa.String(length=100), nullable=True),
    sa.Column('pine_script_config', sa.String(length=100), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tv_symbol')
    )
    op.create_index('ix_symbol_maps_tv_symbol_active', 'symbol_maps', ['tv_symbol', 'active'], unique=False)
    op.create_table('normalized_signals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('raw_signal_id', sa.Uuid(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('strategy_id', sa.String(length=100), nullable=False),
    sa.Column('ticker_received', sa.String(length=50), nullable=False),
    sa.Column('mapped_symbol', sa.String(length=50), nullable=True),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('sentiment', sa.String(length=20), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('price', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('timeframe', sa.String(length=20), nullable=True),
    sa.Column('signal_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('signal_role', sa.String(length=30), nullable=True),
    sa.Column('dedupe_key', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('normalized_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['raw_signal_id'], ['raw_signals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedupe_key')
    )
    op.create_index('ix_normalized_signals_signal_ts', 'normalized_signals', ['signal_ts'], unique=False)
    op.create_index('ix_normalized_signals_strategy_id', 'normalized_signals', ['strategy_id'], unique=False)
    op.create_table('strategies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('strategy_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('asset_symbol', sa.String(length=50), nullable=True),
    sa.Column('timeframe', sa.String(length=20), nullable=True),
    sa.Column('strategy_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('webhook_token', sa.String(length=128), nullable=True),
    sa.Column('traderspost_webhook_url', sa.Text(), nullable=True),
    sa.Column('template_id', sa.Uuid(), nullable=True),
    sa.Column('pine_script_ticker_note', sa.Text(), nullable=True),
    sa.Column('luxalgo_metrics_json', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('retired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retired_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['strategy_templates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('strategy_id')
    )
    op.create_index('ix_strategies_status', 'strategies', ['status'], unique=False)
    op.create_table('conflict_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('strategy_id_a', sa.String(length=100), nullable=False),
    sa.Column('strategy_id_b', sa.String(length=100), nullable=True),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('direction_a', sa.String(length=10), nullable=True),
    sa.Column('direction_b', sa.String(length=10), nullable=True),
    sa.Column('score_a', sa.Integer(), nullable=True),
    sa.Column('score_b', sa.Integer(), nullable=True),
    sa.Column('signal_a_id', sa.Uuid(), nullable=False),
    sa.Column('signal_b_id', sa.Uuid(), nullable=True),
    sa.Column('conflict_type', sa.String(length=50), nullable=False),
    sa.Column('resolution', sa.String(length=50), nullable=False),
    sa.Column('resolution_reason', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['signal_a_id'], ['normalized_signals.id'], ),
    sa.ForeignKeyConstraint(['signal_b_id'], ['normalized_signals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('strategy_decisions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('normalized_signal_id', sa.Uuid(), nullable=False),
    sa.Column('strategy_id', sa.String(length=100), nullable=False),
    sa.Column('outcome', sa.String(length=30), nullable=False),
    sa.Column('block_reason', sa.String(length=100), nullable=True),
    sa.Column('block_level', sa.Integer(), nullable=True),
    sa.Column('reason_detail', sa.Text(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('score_breakdown_json', sa.JSON(), nullable=True),
    sa.Column('pipeline_execution_json', sa.JSON(), nullable=True),
    sa.Column('sl_price', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('tp_price', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('atr_value', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('sl_multiplier_used', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('market_data_provider', sa.String(length=50), nullable=True),
    sa.Column('config_snapshot_json', sa.JSON(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['normalized_signal_id'], ['normalized_signals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_strategy_decisions_created_at', 'strategy_decisions', ['created_at'], unique=False)
    op.create_index('ix_strategy_decisions_normalized_signal_id', 'strategy_decisions', ['normalized_signal_id'], unique=False)
    op.create_index('ix_strategy_decisions_outcome', 'strategy_decisions', ['outcome'], unique=False)
    op.create_index('ix_strategy_decisions_strategy_id', 'strategy_decisions', ['strategy_id'], unique=False)
    op.create_table('strategy_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('strategy_id', sa.String(length=100), nullable=False),
    sa.Column('profile_name', sa.String(length=100), nullable=True),
    sa.Column('traderspost_webhook_url', sa.Text(), nullable=True),
    sa.Column('traderspost_enabled', sa.Boolean(), nullable=False),
    sa.Column('dry_run', sa.Boolean(), nullable=False),
    sa.Column('routing_mode', sa.String(length=30), nullable=False),
    sa.Column('allowed_accounts_json', sa.JSON(), nullable=True),
    sa.Column('allowed_symbols_json', sa.JSON(), nullable=True),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('pipeline_config_json', sa.JSON(), nullable=True),
    sa.Column('sl_atr_multiplier', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('tp_atr_multiplier', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('atr_period', sa.Integer(), nullable=True),
    sa.Column('atr_timeframe', sa.String(length=10), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('days_enabled_json', sa.JSON(), nullable=True),
    sa.Column('entry_start_time', sa.Time(), nullable=True),
    sa.Column('entry_end_time', sa.Time(), nullable=True),
    sa.Column('allow_exits_outside_window', sa.Boolean(), nullable=True),
    sa.Column('allow_overnight', sa.Boolean(), nullable=True),
    sa.Column('force_flat_time', sa.Time(), nullable=True),
    sa.Column('max_holding_minutes', sa.Integer(), nullable=True),
    sa.Column('cooldown_minutes', sa.Integer(), nullable=True),
    sa.Column('max_trades_day', sa.Integer(), nullable=True),
    sa.Column('daily_loss_stop', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('daily_profit_lock', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('max_quantity', sa.Integer(), nullable=True),
    sa.Column('max_open_positions_symbol', sa.Integer(), nullable=True),
    sa.Column('allow_reversal', sa.Boolean(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.strategy_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('strategy_id')
    )
    op.create_table('webhook_deliveries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('decision_id', sa.Uuid(), nullable=False),
    sa.Column('strategy_id', sa.String(length=100), nullable=False),
    sa.Column('destination', sa.String(length=50), nullable=False),
    sa.Column('url_masked', sa.String(length=200), nullable=True),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('response_status_code', sa.Integer(), nullable=True),
    sa.Column('response_body', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['strategy_decisions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_webhook_deliveries_created_at', 'webhook_deliveries', ['created_at'], unique=False)
    op.create_index('ix_webhook_deliveries_status', 'webhook_deliveries', ['status'], unique=False)
    op.create_index('ix_webhook_deliveries_strategy_id', 'webhook_deliveries', ['strategy_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_webhook_deliveries_strategy_id', table_name='webhook_deliveries')
    op.drop_index('ix_webhook_deliveries_status', table_name='webhook_deliveries')
    op.drop_index('ix_webhook_deliveries_created_at', table_name='webhook_deliveries')
    op.drop_table('webhook_deliveries')
    op.drop_table('strategy_profiles')
    op.drop_index('ix_strategy_decisions_strategy_id', table_name='strategy_decisions')
    op.drop_index('ix_strategy_decisions_outcome', table_name='strategy_decisions')
    op.drop_index('ix_strategy_decisions_normalized_signal_id', table_name='strategy_decisions')
    op.drop_index('ix_strategy_decisions_created_at', table_name='strategy_decisions')
    op.drop_table('strategy_decisions')
    op.drop_table('conflict_logs')
    op.drop_index('ix_strategies_status', table_name='strategies')
    op.drop_table('strategies')
    op.drop_index('ix_normalized_signals_strategy_id', table_name='normalized_signals')
    op.drop_index('ix_normalized_signals_signal_ts', table_name='normalized_signals')
    op.drop_table('normalized_signals')
    op.drop_index('ix_symbol_maps_tv_symbol_active', table_name='symbol_maps')
    op.drop_table('symbol_maps')
    op.drop_table('strategy_templates')
    op.drop_table('strategy_performance')
    op.drop_index('ix_raw_signals_strategy_id', table_name='raw_signals')
    op.drop_index('ix_raw_signals_received_at', table_name='raw_signals')
    op.drop_table('raw_signals')
    op.drop_table('position_states')
    op.drop_index('ix_ohlcv_bars_symbol_tf_time', table_name='ohlcv_bars')
    op.drop_table('ohlcv_bars')
    op.drop_table('market_data_status')
    op.drop_table('global_profile')
    op.drop_index('ix_economic_events_impact', table_name='economic_events')
    op.drop_index('ix_economic_events_event_time', table_name='economic_events')
    op.drop_table('economic_events')
    op.drop_index('ix_audit_logs_object_type_id', table_name='audit_logs')
    op.drop_index('ix_audit_logs_created_at', table_name='audit_logs')
    op.drop_index('ix_audit_logs_actor', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('asset_profiles')
    # ### end Alembic commands ###
