"""add_market_data_symbol_to_symbol_map

Revision ID: a1029493ee79
Revises: d14b378f0c8d
Create Date: 2026-06-17 22:10:29.519365+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1029493ee79'
down_revision: Union[str, None] = 'd14b378f0c8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('symbol_maps', sa.Column('market_data_symbol', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('symbol_maps', 'market_data_symbol')
    # ### end Alembic commands ###
